title: Skerry Technologies
description: >- # this means to ignore newlines until "baseurl:"
Nicholas Weaver's Skerry Technologies: Mad Science in Action  
baseurl: ""
url: "https://skerry-tech.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed

incremental: true

keep_files: [.git, CNAME]
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

